version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./prisma:/app/prisma

  database:
    image: alpine:latest
    command: >
      sh -c "
        apk add --no-cache sqlite &&
        mkdir -p /data &&
        touch /data/dev.db &&
        tail -f /dev/null
      "
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
